select * from maps.geological_sample;
	select * from sisbndo.tb_analise_sedimentologica;
	select * from sisbndo.tb_ar_superior;
	select * from sisbndo.tb_batimetria;
	select * from sisbndo.tb_coleta_perfil;
	select * from sisbndo.tb_coleta_perfil_espaco_tempo;
select * from maps.commission;
select * from maps.datum;
select * from maps.equipment;
	select * from sisbndo.tb_equipamento_comissao;
select * from maps.station;
	select * from sisbndo.tb_estacao;
	select * from sisbndo.tb_estacao_espaco_tempo;
--select * from sisbndo.tb_gebco_raw;--VAZIA
select * from maps.institution;
select * from maps.hydrographic_survey;
--select * from sisbndo.tb_meteorologia;--VAZIA
--select * from sisbndo.tb_meteorologia_espaco_tempo tmet ;--VAZIA
select * from maps.media;
--SELECT cod_equipamento, cod_midia, cod_comissao, bruto FROM sisbndo.tb_midia_equipamento_comissao;--7 registros
select * from sisbndo.tb_
--select * from maps.country;
select * from maps.researcher;
select * from maps.research;
select * from maps.platform;
--select * from sisbndo.tb_plataforma_comissao;
select * from maps.harbor;
select * from maps.project;
select * from maps.seismic;
select * from maps.equipment_category;
select * from maps.station_category;
select * from maps.media_category;
select * from maps.platform_category;
