package com.maps.persistence.model.bndo;

import com.maps.persistence.model.GenericAuditEntity;
import jakarta.persistence.Entity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.hibernate.envers.Audited;

@Audited @Entity @Data @AllArgsConstructor @NoArgsConstructor @EqualsAndHashCode(callSuper = true)
public class SedimentologicalAnalysis extends GenericAuditEntity {

    private int cod_amostra_geologica;
    private int num_analise;
    private int b;
    private int co;
    private int cod_laboratorio;
    private int cr;
    private int data_analise;
    private int data_remessa;
    private int e;
    private int espessura;
    private int f;
    private int floculacao;
    private int g;
    private int gc;
    private int idade_geologica;
    private int l;
    private int maturidade;
    private int metodo_analise_mineral;
    private int metodo_datacao;
    private int metodologia_c1;
    private int metodologia_c2;
    private int metodologia_d1;
    private int metodologia_d2;
    private int metodologia_e;
    private int metodologia_f;
    private int metodologia_m1;
    private int metodologia_m2;
    private int metodologia_p1;
    private int metodologia_p2;
    private int metodologia_r;
    private int metodologia_t;
    private int morfom_a;
    private int morfom_e;
    private int morfom_f;
    private int o1;
    private int o2;
    private int p;
    private int s;
    private int peso_analise;
    private int percentual_carbonato;
    private int obs_analise;
    private int per_05_dist_gran;
    private int per_16_dist_gran;
    private int per_25_dist_gran;
    private int per_50_dist_gran;
    private int per_75_dist_gran;
    private int per_84_dist_gran;
    private int per_95_dist_gran;
    private int par_assimetria;
    private int par_curtose;
    private int par_desvio_padrao;
    private int par_diametro_medio;
    private int par_mediana;
    private int per_areia;
    private int per_argila;
    private int per_cascalho;
    private int per_silte;
    private int cod_banco;
    private int num_arquivo;
    private int comprimento_coletado;
}
